
version: '3'

services:
  # Frontend React application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://backend:3001
    depends_on:
      - backend
    volumes:
      - ./:/app
      - /app/node_modules

  # Backend Express server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3001
      - CLIENT_URL=http://localhost:8080
      - NODE_ENV=production
