// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpbmlyfwfvedfmvtuehd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwYm1seWZ3ZnZlZGZtdnR1ZWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NTI5MTUsImV4cCI6MjA1NzUyODkxNX0.igFY12tH6xhCf7aobI192fkVhUcGwGxcpiw1p0prdsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);